# Default configuration for ncrsh

data:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  shuffle: true

training:
  learning_rate: 0.001
  epochs: 10
  weight_decay: 0.01
  momentum: 0.9
  nesterov: true

model:
  hidden_size: 256
  num_layers: 3
  dropout: 0.1
  activation: 'relu'

logging:
  log_dir: '../logs'
  log_level: 'INFO'
  save_checkpoints: true
  checkpoint_dir: '../checkpoints'
  save_every: 1

device: 'cuda'  # or 'cpu'
